try:
    print("Enterd in try ")
    print(29/0)

except:
    print("got the error")

print("completed")